apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yarn
spec:
  description: Run yarn tasks
  params:
    - default: .
      description: The path where package.json of the project is defined.
      name: PATH_CONTEXT
      type: string
    - default: install
      description: The yarn script you want to run.
      name: SCRIPT
      type: string
    - default: 'registry.redhat.io/rhel9/nodejs-20:latest'
      description: The node image you want to use.
      name: IMAGE
      type: string
  steps:
    - computeResources: {}
      image: $(params.IMAGE)
      name: yarn
      script: |
        npm install --global yarn && yarn $(params.SCRIPT)
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
  workspaces:
    - name: source
