apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rhdh-plugin
spec:
  workspaces:
    - name: source
    - name: npmrc
      optional: true

  params:

    - name: GIT_URL
      type: string
      default: https://github.com/daferoli/backstage-plugin-scaffolder-global-variables
    - name: GIT_REVISION
      type: string
      default: main

  tasks:

  - name: git-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: $(params.GIT_URL)
      - name: revision
        value: $(params.GIT_REVISION)
    workspaces:
      - name: output
        workspace: source

  - name: yarn-install
    taskRef:
      name: npm
      kind: Task
    runAfter: 
      - git-clone
    params:
      - name: COMMAND
        value: install --global yarn && yarn install
    workspaces:
      - name: source
        workspace: source

  - name: publish-package
    taskRef:
      name: npm
      kind: Task
    runAfter:
      - yarn-install
    params:
      - name: COMMAND
        value: publish
    workspaces:
      - name: source
        workspace: source
      - name: npmrc
        workspace: npmrc
